[package]
name = "dashql-pack"
version = "0.0.2-dev.17"
description = "Packaging tool for get.dashql.app"
edition = "2021"
rust-version = "1.70"
workspace = "../../"

[dev-dependencies]
tauri-build = "2.3.1"
tauri-plugin-updater = "2.9.0"

[dependencies]
futures = "0.3.31"
chrono = "0.4.41"
anyhow = "1.0.99"
semver = "1.0.26"
aws-sdk-s3 = "1.102.0"
aws-credential-types = "1.2.5"
log = "0.4.27"
env_logger = "0.11.8"
git2 = "0.20.2"
regex = "1.11.1"
lazy_static = "1.5.0"
minisign = "0.7.9"

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.142"
features = ["preserve_order"]

[dependencies.serde_with]
version = "3.14.0"
features = ["json"]

[dependencies.aws-config]
version = "1.8.5"

[dependencies.tokio]
version = "1.47.1"
features = ["full"]

[dependencies.clap]
version = "4.5.45"
features = ["derive"]

[dependencies.uuid]
version = "1.17.0"
features = ["v5"]

[dependencies.toml]
version = "0.8.23"
features = ["preserve_order"]
